### ISSUE TITLE
Error: module.js:339

### ISSUE THREAD

**Issue by ghost** [hudochenkov/sublime-postcss-sorting#5]
Just now, I've installed **PostCSS** via Package Control for Sublime Text 3. In former times it did work, but now there is the following error:

```
PostCSS Sorting
Error: module.js:339
    throw err;
    ^

Error: Cannot find module './terminal-highlight'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/pl/Library/Application Support/Sublime Text 3/Packages/PostCSS Sorting/node_modules/postcss/lib/css-syntax-error.js:15:26)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

```
How can this be solved?

**Comment by jtwee** [comment]
I'm getting a variation on the same error with Sublime Text 3. It worked before the update with no configuration. Now I get the following error:
```
error: PostCSS Sorting
Error: module.js:457
    throw err;
    ^

Error: Cannot find module './terminal-highlight'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jeremy.tweddle/Library/Application Support/Sublime Text 3/Packages/PostCSS Sorting/node_modules/postcss/lib/css-syntax-error.js:15:26)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

I simplified my CSS to the following for testing and the same error occurred.
```
body {
    height: 100%;
    font-size: 14px;
}
```

**Comment by ghost** [comment]
I've tested it with a SCSS and with a CSS file and getting the same error. The are no issues with the files.

**Comment by jtwee** [comment]
I tested my basic css file with `postcss-cli` using `postcss-sorting` as a plugin (and default.json as options) and it worked as expected.

**Comment by hudochenkov** [comment]
Thank you for reporting and testing! I'm using Github Desktop client and it didn't show a lot of not committed files in node_modules. Now I published `2.0.1` with full node_modules. I believe, problem will be solved. But let's wait until package will be updated to `2.0.1` at https://packagecontrol.io/packages/PostCSS%20Sorting

**Comment by hudochenkov** [comment]
`2.0.1` is published.

**Comment by jtwee** [comment]
Updated to 2.0.1 and working perfectly for me now.

Thanks!

**Comment by ghost** [comment]
Updated to `2.0.1` and is working for me, too.

Thanks!

**Comment by hudochenkov** [comment]
Thanks for reporting! Sorry for inconvenience.

**Comment by ghost** [comment]
It wasn't a inconvenience. It was just a little impatience.

Thank you very much for the support!
